### ISSUE TITLE
ConcurrentModificationException in Domain Registry

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-registry-domain#16]
We are getting this problem when using the HypertyConnector. And when it happens we can't search the email.

```shell
2016-05-02 13:07:48 INFO  RamClient:45 - Removed hyperty hyperty://hybroker.rethink.ptinovacao.pt/f92c529b-b923-4ed3-8ec1-76bc46d64272 from user://gmail.com/micaelpedrosa
[qtp1950953603-23] ERROR spark.webserver.MatcherFilter - 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at domainregistry.HypertyService.deleteExpiredHyperties(HypertyService.java:82)
	at domainregistry.HypertyService.getAllHyperties(HypertyService.java:32)
	at domainregistry.HypertyController.lambda$new$1(HypertyController.java:44)
	at spark.SparkBase$1.handle(SparkBase.java:311)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159)
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ruijose** [comment]
Ended up switching HashMap by ConcurrentHashMap. If the error still persists reopen the issue.
